### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by tewebb** [Shwaffle/Encounter-Sheet-Imports#2]
Attempting to run the script file results in a an error:
..\Encounter-Sheet-Imports-master\templates.js:4
                                ability: ,
                                         ^

SyntaxError: Unexpected token ,
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by MattBerg11** [comment]
Hello,

These scripts are in no way intended to be ran outside the PDF that they are contained in. Additionally, the templates file is both incomplete, and non-functioning. It is, as the name states, a template for when I am making parts of the data files.
